using System.Text;

namespace MyCodeGent.Templates;

public static class FileUploadTemplate
{
    public static string GenerateFileStorageService(string rootNamespace)
    {
        var sb = new StringBuilder();
        
        sb.AppendLine("using Microsoft.AspNetCore.Http;");
        sb.AppendLine();
        sb.AppendLine($"namespace {rootNamespace}.Application.Common.Interfaces;");
        sb.AppendLine();
        sb.AppendLine("public interface IFileStorageService");
        sb.AppendLine("{");
        sb.AppendLine("    Task<string> UploadFileAsync(IFormFile file, string folder, CancellationToken cancellationToken = default);");
        sb.AppendLine("    Task<byte[]> DownloadFileAsync(string filePath, CancellationToken cancellationToken = default);");
        sb.AppendLine("    Task<bool> DeleteFileAsync(string filePath, CancellationToken cancellationToken = default);");
        sb.AppendLine("    Task<bool> FileExistsAsync(string filePath, CancellationToken cancellationToken = default);");
        sb.AppendLine("    string GetFileUrl(string filePath);");
        sb.AppendLine("}");
        
        return sb.ToString();
    }
    
    public static string GenerateLocalFileStorageService(string rootNamespace)
    {
        var sb = new StringBuilder();
        
        sb.AppendLine("using Microsoft.AspNetCore.Http;");
        sb.AppendLine("using Microsoft.Extensions.Configuration;");
        sb.AppendLine($"using {rootNamespace}.Application.Common.Interfaces;");
        sb.AppendLine();
        sb.AppendLine($"namespace {rootNamespace}.Infrastructure.Services;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Local file system storage implementation");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public class LocalFileStorageService : IFileStorageService");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly string _uploadPath;");
        sb.AppendLine("    private readonly string _baseUrl;");
        sb.AppendLine();
        sb.AppendLine("    public LocalFileStorageService(IConfiguration configuration)");
        sb.AppendLine("    {");
        sb.AppendLine("        _uploadPath = configuration[\"FileStorage:UploadPath\"] ?? \"uploads\";");
        sb.AppendLine("        _baseUrl = configuration[\"FileStorage:BaseUrl\"] ?? \"/uploads\";");
        sb.AppendLine("        ");
        sb.AppendLine("        // Ensure upload directory exists");
        sb.AppendLine("        if (!Directory.Exists(_uploadPath))");
        sb.AppendLine("        {");
        sb.AppendLine("            Directory.CreateDirectory(_uploadPath);");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public async Task<string> UploadFileAsync(IFormFile file, string folder, CancellationToken cancellationToken = default)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (file == null || file.Length == 0)");
        sb.AppendLine("            throw new ArgumentException(\"File is empty\", nameof(file));");
        sb.AppendLine();
        sb.AppendLine("        // Create folder if it doesn't exist");
        sb.AppendLine("        var folderPath = Path.Combine(_uploadPath, folder);");
        sb.AppendLine("        if (!Directory.Exists(folderPath))");
        sb.AppendLine("        {");
        sb.AppendLine("            Directory.CreateDirectory(folderPath);");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        // Generate unique filename");
        sb.AppendLine("        var extension = Path.GetExtension(file.FileName);");
        sb.AppendLine("        var fileName = $\"{Guid.NewGuid()}{extension}\";");
        sb.AppendLine("        var filePath = Path.Combine(folder, fileName);");
        sb.AppendLine("        var fullPath = Path.Combine(_uploadPath, filePath);");
        sb.AppendLine();
        sb.AppendLine("        // Save file");
        sb.AppendLine("        using (var stream = new FileStream(fullPath, FileMode.Create))");
        sb.AppendLine("        {");
        sb.AppendLine("            await file.CopyToAsync(stream, cancellationToken);");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        return filePath.Replace(\"\\\\\", \"/\");");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public async Task<byte[]> DownloadFileAsync(string filePath, CancellationToken cancellationToken = default)");
        sb.AppendLine("    {");
        sb.AppendLine("        var fullPath = Path.Combine(_uploadPath, filePath);");
        sb.AppendLine("        ");
        sb.AppendLine("        if (!File.Exists(fullPath))");
        sb.AppendLine("            throw new FileNotFoundException(\"File not found\", filePath);");
        sb.AppendLine();
        sb.AppendLine("        return await File.ReadAllBytesAsync(fullPath, cancellationToken);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public Task<bool> DeleteFileAsync(string filePath, CancellationToken cancellationToken = default)");
        sb.AppendLine("    {");
        sb.AppendLine("        var fullPath = Path.Combine(_uploadPath, filePath);");
        sb.AppendLine("        ");
        sb.AppendLine("        if (File.Exists(fullPath))");
        sb.AppendLine("        {");
        sb.AppendLine("            File.Delete(fullPath);");
        sb.AppendLine("            return Task.FromResult(true);");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        return Task.FromResult(false);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public Task<bool> FileExistsAsync(string filePath, CancellationToken cancellationToken = default)");
        sb.AppendLine("    {");
        sb.AppendLine("        var fullPath = Path.Combine(_uploadPath, filePath);");
        sb.AppendLine("        return Task.FromResult(File.Exists(fullPath));");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public string GetFileUrl(string filePath)");
        sb.AppendLine("    {");
        sb.AppendLine("        return $\"{_baseUrl}/{filePath.Replace(\"\\\\\", \"/\")}\";");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        
        return sb.ToString();
    }
    
    public static string GenerateFileUploadController(string rootNamespace)
    {
        var sb = new StringBuilder();
        
        sb.AppendLine("using Microsoft.AspNetCore.Http;");
        sb.AppendLine("using Microsoft.AspNetCore.Mvc;");
        sb.AppendLine($"using {rootNamespace}.Application.Common.Interfaces;");
        sb.AppendLine();
        sb.AppendLine($"namespace {rootNamespace}.Api.Controllers;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Handles file upload and download operations");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("[ApiController]");
        sb.AppendLine("[Route(\"api/[controller]\")]");
        sb.AppendLine("public class FilesController : ControllerBase");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly IFileStorageService _fileStorage;");
        sb.AppendLine("    private readonly ILogger<FilesController> _logger;");
        sb.AppendLine();
        sb.AppendLine("    public FilesController(IFileStorageService fileStorage, ILogger<FilesController> logger)");
        sb.AppendLine("    {");
        sb.AppendLine("        _fileStorage = fileStorage;");
        sb.AppendLine("        _logger = logger;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Upload a file");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    [HttpPost(\"upload\")]");
        sb.AppendLine("    [ProducesResponseType(typeof(FileUploadResponse), StatusCodes.Status200OK)]");
        sb.AppendLine("    [ProducesResponseType(StatusCodes.Status400BadRequest)]");
        sb.AppendLine("    [RequestSizeLimit(10 * 1024 * 1024)] // 10MB limit");
        sb.AppendLine("    public async Task<IActionResult> Upload(IFormFile file, [FromQuery] string folder = \"general\")");
        sb.AppendLine("    {");
        sb.AppendLine("        try");
        sb.AppendLine("        {");
        sb.AppendLine("            if (file == null || file.Length == 0)");
        sb.AppendLine("                return BadRequest(new { error = \"No file provided\" });");
        sb.AppendLine();
        sb.AppendLine("            // Validate file size (10MB)");
        sb.AppendLine("            if (file.Length > 10 * 1024 * 1024)");
        sb.AppendLine("                return BadRequest(new { error = \"File size exceeds 10MB limit\" });");
        sb.AppendLine();
        sb.AppendLine("            // Validate file extension");
        sb.AppendLine("            var allowedExtensions = new[] { \".jpg\", \".jpeg\", \".png\", \".gif\", \".pdf\", \".doc\", \".docx\", \".xls\", \".xlsx\" };");
        sb.AppendLine("            var extension = Path.GetExtension(file.FileName).ToLowerInvariant();");
        sb.AppendLine("            ");
        sb.AppendLine("            if (!allowedExtensions.Contains(extension))");
        sb.AppendLine("                return BadRequest(new { error = $\"File type {extension} is not allowed\" });");
        sb.AppendLine();
        sb.AppendLine("            var filePath = await _fileStorage.UploadFileAsync(file, folder);");
        sb.AppendLine("            var fileUrl = _fileStorage.GetFileUrl(filePath);");
        sb.AppendLine();
        sb.AppendLine("            _logger.LogInformation(\"File uploaded: {FileName} -> {FilePath}\", file.FileName, filePath);");
        sb.AppendLine();
        sb.AppendLine("            return Ok(new FileUploadResponse");
        sb.AppendLine("            {");
        sb.AppendLine("                FileName = file.FileName,");
        sb.AppendLine("                FilePath = filePath,");
        sb.AppendLine("                FileUrl = fileUrl,");
        sb.AppendLine("                FileSize = file.Length,");
        sb.AppendLine("                ContentType = file.ContentType");
        sb.AppendLine("            });");
        sb.AppendLine("        }");
        sb.AppendLine("        catch (Exception ex)");
        sb.AppendLine("        {");
        sb.AppendLine("            _logger.LogError(ex, \"Error uploading file\");");
        sb.AppendLine("            return StatusCode(500, new { error = \"Error uploading file\" });");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Download a file");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    [HttpGet(\"download/{*filePath}\")]");
        sb.AppendLine("    [ProducesResponseType(StatusCodes.Status200OK)]");
        sb.AppendLine("    [ProducesResponseType(StatusCodes.Status404NotFound)]");
        sb.AppendLine("    public async Task<IActionResult> Download(string filePath)");
        sb.AppendLine("    {");
        sb.AppendLine("        try");
        sb.AppendLine("        {");
        sb.AppendLine("            if (!await _fileStorage.FileExistsAsync(filePath))");
        sb.AppendLine("                return NotFound(new { error = \"File not found\" });");
        sb.AppendLine();
        sb.AppendLine("            var fileBytes = await _fileStorage.DownloadFileAsync(filePath);");
        sb.AppendLine("            var fileName = Path.GetFileName(filePath);");
        sb.AppendLine("            var contentType = GetContentType(fileName);");
        sb.AppendLine();
        sb.AppendLine("            return File(fileBytes, contentType, fileName);");
        sb.AppendLine("        }");
        sb.AppendLine("        catch (Exception ex)");
        sb.AppendLine("        {");
        sb.AppendLine("            _logger.LogError(ex, \"Error downloading file: {FilePath}\", filePath);");
        sb.AppendLine("            return StatusCode(500, new { error = \"Error downloading file\" });");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Delete a file");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    [HttpDelete(\"{*filePath}\")]");
        sb.AppendLine("    [ProducesResponseType(StatusCodes.Status204NoContent)]");
        sb.AppendLine("    [ProducesResponseType(StatusCodes.Status404NotFound)]");
        sb.AppendLine("    public async Task<IActionResult> Delete(string filePath)");
        sb.AppendLine("    {");
        sb.AppendLine("        try");
        sb.AppendLine("        {");
        sb.AppendLine("            var deleted = await _fileStorage.DeleteFileAsync(filePath);");
        sb.AppendLine("            ");
        sb.AppendLine("            if (!deleted)");
        sb.AppendLine("                return NotFound(new { error = \"File not found\" });");
        sb.AppendLine();
        sb.AppendLine("            _logger.LogInformation(\"File deleted: {FilePath}\", filePath);");
        sb.AppendLine("            return NoContent();");
        sb.AppendLine("        }");
        sb.AppendLine("        catch (Exception ex)");
        sb.AppendLine("        {");
        sb.AppendLine("            _logger.LogError(ex, \"Error deleting file: {FilePath}\", filePath);");
        sb.AppendLine("            return StatusCode(500, new { error = \"Error deleting file\" });");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private static string GetContentType(string fileName)");
        sb.AppendLine("    {");
        sb.AppendLine("        var extension = Path.GetExtension(fileName).ToLowerInvariant();");
        sb.AppendLine("        return extension switch");
        sb.AppendLine("        {");
        sb.AppendLine("            \".jpg\" or \".jpeg\" => \"image/jpeg\",");
        sb.AppendLine("            \".png\" => \"image/png\",");
        sb.AppendLine("            \".gif\" => \"image/gif\",");
        sb.AppendLine("            \".pdf\" => \"application/pdf\",");
        sb.AppendLine("            \".doc\" => \"application/msword\",");
        sb.AppendLine("            \".docx\" => \"application/vnd.openxmlformats-officedocument.wordprocessingml.document\",");
        sb.AppendLine("            \".xls\" => \"application/vnd.ms-excel\",");
        sb.AppendLine("            \".xlsx\" => \"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet\",");
        sb.AppendLine("            _ => \"application/octet-stream\"");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("public class FileUploadResponse");
        sb.AppendLine("{");
        sb.AppendLine("    public string FileName { get; set; } = string.Empty;");
        sb.AppendLine("    public string FilePath { get; set; } = string.Empty;");
        sb.AppendLine("    public string FileUrl { get; set; } = string.Empty;");
        sb.AppendLine("    public long FileSize { get; set; }");
        sb.AppendLine("    public string ContentType { get; set; } = string.Empty;");
        sb.AppendLine("}");
        
        return sb.ToString();
    }
}
